### ISSUE TITLE
Why did the miui framework(in /android) have stopped update for about 5 months?

### ISSUE THREAD

**Issue by kqstone** [MiCode/patchrom_android#2]
Dear

In the patchrom guide, you said update the miui code to target device by  running "tools/git.patch abcdefg..hijklmn > patch.file"...
But I can't found the newest android/framework. And I checked the git website,  it has stopped update for about 5 months. 
So how can we do the updates, or I misunderstanded the actual meaning.

Regards

**Comment by yu88my** [comment]
Sorry, I didn't notice the error caused by an exception when push /android, now i had updated the /android. Enjoy.

**Comment by kqstone** [comment]
Thank you!
I retried it, and found that "../tools/git.patch 3fdbdfb198..a1b023e5de >patch.files" worked well. But when applied patch with this command "../tools/git.apply < ../android/patch.files" in target device directory, it didn't work and threw exception "error: No changes". Waiting for your reply.

Regards

**Comment by yu88my** [comment]
you should run that command like this "../tools/git.apply ../android/patch.files"

**Comment by kqstone** [comment]
It worked. Thank you!
